In [1]:
'''

配对的std试次多于odd试次，odd试次不动，对每一个std进行抽样。

每个被试有八种数据4对数据，全部读进来。

'''


import os.path as op
import mne
from mne.preprocessing import ICA
import matplotlib.pyplot as plt
from copy import deepcopy
import numpy as np

In [3]:
sub_ids = [

    'pre4007_y','pre4008_y','pre4009_y','pre4010_y','pre4011_y','pre4012_y','pre4013_y','pre4014_y',

]

sub_ids = [

    'pre4014_y',

]

'''
从 clean到equalization
'''
data_path = '.\data\\6epoch_clean_oddball\\'


'''

有八种刺激条件，每种都给出一个list，所有被试的都放进去。

'''
list_epochs_clean_oddball_std_BA = list()
list_epochs_clean_oddball_odd_TA = list()
list_epochs_clean_oddball_std_ta = list()
list_epochs_clean_oddball_odd_ba = list()
list_epochs_clean_oddball_std_t1ji = list()
list_epochs_clean_oddball_odd_t4ji= list()
list_epochs_clean_oddball_std_t4ji = list()
list_epochs_clean_oddball_odd_t1ji = list()

'''

每个被试的数据拆分出来放到list里

'''
for sub_id in sub_ids:
    fname = data_path + sub_id + '_std_BA-epo.fif'
    epochs = mne.read_epochs(fname)
    print(epochs.events)
    list_epochs_clean_oddball_std_BA.append(epochs)

    fname = data_path + sub_id + '_odd_TA-epo.fif'
    epochs = mne.read_epochs(fname)
    list_epochs_clean_oddball_odd_TA.append(epochs)

    # fname = data_path + sub_id + '_std_ta-epo.fif'
    # epochs = mne.read_epochs(fname)
    # list_epochs_clean_oddball_std_ta.append(epochs)
    #
    # fname = data_path + sub_id + '_odd_ba-epo.fif'
    # epochs = mne.read_epochs(fname)
    # list_epochs_clean_oddball_odd_ba.append(epochs)

    fname = data_path + sub_id + '_std_t1ji-epo.fif'
    epochs = mne.read_epochs(fname)
    list_epochs_clean_oddball_std_t1ji.append(epochs)

    fname = data_path + sub_id + '_odd_t4ji-epo.fif'
    epochs = mne.read_epochs(fname)
    list_epochs_clean_oddball_odd_t4ji.append(epochs)

    # fname = data_path + sub_id + '_std_t4ji-epo.fif'
    # epochs = mne.read_epochs(fname)
    # list_epochs_clean_oddball_std_t4ji.append(epochs)
    #
    # fname = data_path + sub_id + '_odd_t1ji-epo.fif'
    # epochs = mne.read_epochs(fname)
    # list_epochs_clean_oddball_odd_t1ji.append(epochs)

Reading E:\实验\阅读困难\数据处理\pre4\data\6epoch_clean_oddball\pre4014_y_std_BA-epo.fif ...
    Found the data of interest:
        t =    -500.00 ...    1000.00 ms
        0 CTF compensation matrices available
Not setting metadata
379 matching events found
No baseline correction applied
0 projection items activated
[[3670434       0       1]
 [3671934       0       1]
 [3673434       0       1]
 ...
 [4314237       0       1]
 [4315670       0       1]
 [4318703       0       1]]
Reading E:\实验\阅读困难\数据处理\pre4\data\6epoch_clean_oddball\pre4014_y_odd_TA-epo.fif ...
    Found the data of interest:
        t =    -500.00 ...    1000.00 ms
        0 CTF compensation matrices available
Not setting metadata
47 matching events found
No baseline correction applied
0 projection items activated
Reading E:\实验\阅读困难\数据处理\pre4\data\6epoch_clean_oddball\pre4014_y_std_t1ji-epo.fif ...
    Found the data of interest:
        t =    -500.00 ...    1000.00 ms
        0 CTF compensation matrices available
Not sett

In [4]:
'''
配对 concatenate
list_epochs_clean_oddball_std_BA = list()
list_epochs_clean_oddball_odd_TA = list()
list_epochs_clean_oddball_std_ta = list()
list_epochs_clean_oddball_odd_ba = list()
list_epochs_clean_oddball_std_t1ji = list()
list_epochs_clean_oddball_odd_t4ji= list()
list_epochs_clean_oddball_std_t4ji = list()
list_epochs_clean_oddball_odd_t1ji = list()
'''

%matplotlib qt

for num_sub in range(len(sub_ids)):
    '''
    把两种类型的epoch拼接起来方便后面进行平均试次。


equalize_event_counts(event_ids=None, method='mintime')[source]
Equalize the number of trials in each condition.

It tries to make the remaining epochs occurring as close as possible in time. This method works based on the idea that if there happened to be some time-varying (like on the scale of minutes) noise characteristics during a recording, they could be compensated for (to some extent) in the equalization process. This method thus seeks to reduce any of those effects by minimizing the differences in the times of the events within a Epochs instance. For example, if one event type occurred at time points [1, 2, 3, 4, 120, 121] and the another one at [3.5, 4.5, 120.5, 121.5], this method would remove the events at times [1, 2] for the first event type – and not the events at times [120, 121].

    '''
    # 辅音
    epochs_concat_std_BA_odd_TA = mne.concatenate_epochs([list_epochs_clean_oddball_std_BA[num_sub],list_epochs_clean_oddball_odd_TA[num_sub]])
    epochs_concat_std_BA_odd_TA.equalize_event_counts(method='mintime')
    # epochs_concat_std_ta_odd_ba = mne.concatenate_epochs([list_epochs_clean_oddball_std_ta[num_sub],list_epochs_clean_oddball_odd_ba[num_sub]])
    # epochs_concat_std_ta_odd_ba.equalize_event_counts(method='mintime')
    # 音调
    epochs_concat_std_t1ji_odd_t4ji = mne.concatenate_epochs([list_epochs_clean_oddball_std_t1ji[num_sub],list_epochs_clean_oddball_odd_t4ji[num_sub]])
    epochs_concat_std_t1ji_odd_t4ji.equalize_event_counts(method='mintime')
    # epochs_concat_std_t4ji_odd_t1ji = mne.concatenate_epochs([list_epochs_clean_oddball_std_t4ji[num_sub],list_epochs_clean_oddball_odd_t1ji[num_sub]])
    # epochs_concat_std_t4ji_odd_t1ji.equalize_event_counts(method='mintime')

    epochs_clean_oddball_std_BA = epochs_concat_std_BA_odd_TA['1']
    epochs_clean_oddball_odd_TA = epochs_concat_std_BA_odd_TA['2']
    # epochs_clean_oddball_std_ta = epochs_concat_std_ta_odd_ba['3']
    # epochs_clean_oddball_odd_ba = epochs_concat_std_ta_odd_ba['4']
    epochs_clean_oddball_std_t1ji = epochs_concat_std_t1ji_odd_t4ji['3']
    epochs_clean_oddball_odd_t4ji= epochs_concat_std_t1ji_odd_t4ji['4']
    # epochs_clean_oddball_std_t4ji = epochs_concat_std_t4ji_odd_t1ji['7']
    # epochs_clean_oddball_odd_t1ji = epochs_concat_std_t4ji_odd_t1ji['8']


    # 重新拆分开来保存，那么是 八个。
    save_path_epoch_clean = '.\data\\6epoch_equalization_oddball\\'
    save_path_evoked = '.\data\\7evoked_equalization_oddball\\'

    epochs_clean_oddball_std_BA.save(save_path_epoch_clean + sub_ids[num_sub] + '_std_BA-epo.fif', overwrite=True)
    epochs_clean_oddball_std_BA.average().save(save_path_evoked + sub_ids[num_sub] + '_std_BA-ave.fif', overwrite=True)

    epochs_clean_oddball_odd_TA.save(save_path_epoch_clean + sub_ids[num_sub] + '_odd_TA-epo.fif', overwrite=True)
    epochs_clean_oddball_odd_TA.average().save(save_path_evoked + sub_ids[num_sub] + '_odd_TA-ave.fif', overwrite=True)

    # epochs_clean_oddball_std_ta.save(save_path_epoch_clean + sub_ids[num_sub] + '_std_ta-epo.fif', overwrite=True)
    # epochs_clean_oddball_std_ta.average().save(save_path_evoked + sub_ids[num_sub] + '_std_ta-ave.fif', overwrite=True)
    #
    # epochs_clean_oddball_odd_ba.save(save_path_epoch_clean + sub_ids[num_sub] + '_odd_ba-epo.fif', overwrite=True)
    # epochs_clean_oddball_odd_ba.average().save(save_path_evoked + sub_ids[num_sub] + '_odd_ba-ave.fif', overwrite=True)

    epochs_clean_oddball_std_t1ji.save(save_path_epoch_clean + sub_ids[num_sub] + '_std_t1ji-epo.fif', overwrite=True)
    epochs_clean_oddball_std_t1ji.average().save(save_path_evoked + sub_ids[num_sub] + '_std_t1ji-ave.fif', overwrite=True)

    epochs_clean_oddball_odd_t4ji.save(save_path_epoch_clean + sub_ids[num_sub] + '_odd_t4ji-epo.fif', overwrite=True)
    epochs_clean_oddball_odd_t4ji.average().save(save_path_evoked + sub_ids[num_sub] + '_odd_t4ji-ave.fif', overwrite=True)

    # epochs_clean_oddball_std_t4ji.save(save_path_epoch_clean + sub_ids[num_sub] + '_std_t4ji-epo.fif', overwrite=True)
    # epochs_clean_oddball_std_t4ji.average().save(save_path_evoked + sub_ids[num_sub] + '_std_t4ji-ave.fif', overwrite=True)
    #
    # epochs_clean_oddball_odd_t1ji.save(save_path_epoch_clean + sub_ids[num_sub] + '_odd_t1ji-epo.fif', overwrite=True)
    # epochs_clean_oddball_odd_t1ji.average().save(save_path_evoked + sub_ids[num_sub] + '_odd_t1ji-ave.fif', overwrite=True)


Not setting metadata


C:\Users\SilverBullet\AppData\Local\Temp\ipykernel_27000\2121725690.py:27: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  epochs_concat_std_BA_odd_TA = mne.concatenate_epochs([list_epochs_clean_oddball_std_BA[num_sub],list_epochs_clean_oddball_odd_TA[num_sub]])


426 matching events found
Applying baseline correction (mode: mean)
Dropped 332 epochs: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 20

C:\Users\SilverBullet\AppData\Local\Temp\ipykernel_27000\2121725690.py:32: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  epochs_concat_std_t1ji_odd_t4ji = mne.concatenate_epochs([list_epochs_clean_oddball_std_t1ji[num_sub],list_epochs_clean_oddball_odd_t4ji[num_sub]])


426 matching events found
Applying baseline correction (mode: mean)
Dropped 334 epochs: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 20