In [1]:
from scipy.io import loadmat


In [24]:
# 指定要读取的 .mat 文件路径
file_path = "./consonantRDM.mat"  # 将 "path/to/your/file.mat" 替换为实际的文件路径

# 使用 loadmat 函数读取 .mat 文件
data = loadmat(file_path)

print(data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun May 21 21:25:40 2023', '__version__': '1.0', '__globals__': [], 'new_rdm': array([[0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 1.        , 1.        , 0.94029851, 0.94029851,
        0.94029851, 0.94029851, 1.        , 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 1.        , 1.        , 0.94029851, 0.94029851,
        0.94029851, 0.94029851, 1.        , 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 1.        , 1.        , 0.94029851, 0.94029851,
        0.94029851, 0.94029851, 1.        , 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 1.        , 1.        , 0.94029851, 0.94029851,
        0.94029851, 0.94029851, 1.       

In [22]:
# 指定要读取的 .mat 文件路径
file_path = "./toneRDM.mat"  # 将 "path/to/your/file.mat" 替换为实际的文件路径

# 使用 loadmat 函数读取 .mat 文件
data2 = loadmat(file_path)

print(data2)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon May 22 00:33:51 2023', '__version__': '1.0', '__globals__': [], 'final_rdm': array([[0.        , 0.91044776, 0.92647059, 1.        , 0.        ,
        0.91044776, 0.92647059, 1.        , 0.        , 0.91044776,
        0.92647059, 1.        , 0.        , 0.91044776, 0.92647059,
        1.        ],
       [0.91044776, 0.        , 0.93316506, 0.99264706, 0.91044776,
        0.        , 0.93316506, 0.99264706, 0.91044776, 0.        ,
        0.93316506, 0.99264706, 0.91044776, 0.        , 0.93316506,
        0.99264706],
       [0.92647059, 0.93316506, 0.        , 0.83823529, 0.92647059,
        0.93316506, 0.        , 0.83823529, 0.92647059, 0.93316506,
        0.        , 0.83823529, 0.92647059, 0.93316506, 0.        ,
        0.83823529],
       [1.        , 0.99264706, 0.83823529, 0.        , 1.        ,
        0.99264706, 0.83823529, 0.        , 1.        , 0.99264706,
        0.83823529, 0.        , 1.     

In [6]:
# 指定要读取的 .mat 文件路径
file_path = "./alltypeRDM.mat"  # 将 "path/to/your/file.mat" 替换为实际的文件路径

# 使用 loadmat 函数读取 .mat 文件
data3 = loadmat(file_path)['rdm']

print(data3)

[[0.         0.97058824 0.94117647 1.         1.         1.
  1.         1.         0.94117647 0.96875    1.         1.
  1.         1.         1.         1.        ]
 [0.97058824 0.         0.94117647 0.97058824 1.         1.
  1.         1.         1.         0.9375     1.         1.
  1.         1.         1.         1.        ]
 [0.94117647 0.94117647 0.         0.85294118 1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         0.97058824 0.85294118 0.         1.         1.
  1.         1.         1.         1.         0.97058824 0.94117647
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         0.         0.97058824
  0.91176471 1.         1.         1.         1.         1.
  0.79411765 0.91176471 0.97058824 1.        ]
 [1.         1.         1.         1.         0.97058824 0.
  0.97058824 1.         1.         1.         1.         1.
  1.         0.88235294 1.   

In [20]:
import numpy as np

# 创建一个 16x16 的 ndarray
arr = data3

# 生成循环的行名和列名
row_names = np.tile(np.arange(1, 5), 4)
col_names = np.tile(np.arange(1, 5), 4)

# 在数组的左侧和顶部添加一列和一行
arr_with_names = np.pad(arr, ((1, 0), (1, 0)), mode='constant', constant_values=0)

# 在第一行和第一列分别设置行名和列名
arr_with_names[0, 1:] = col_names
arr_with_names[1:, 0] = row_names

# 打印带有循环行名和列名的数组
print(arr_with_names)


[[0.         1.         2.         3.         4.         1.
  2.         3.         4.         1.         2.         3.
  4.         1.         2.         3.         4.        ]
 [1.         0.         0.97058824 0.94117647 1.         1.
  1.         1.         1.         0.94117647 0.96875    1.
  1.         1.         1.         1.         1.        ]
 [2.         0.97058824 0.         0.94117647 0.97058824 1.
  1.         1.         1.         1.         0.9375     1.
  1.         1.         1.         1.         1.        ]
 [3.         0.94117647 0.94117647 0.         0.85294118 1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.        ]
 [4.         1.         0.97058824 0.85294118 0.         1.
  1.         1.         1.         1.         1.         0.97058824
  0.94117647 1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         0.
  0.97058824 0.91176471 1.         1.     

In [18]:
# 将行名和列名相同的单元格的值改为0
for i in range(1, arr_with_names.shape[0]):
    for j in range(1, arr_with_names.shape[1]):
        if arr_with_names[i, 0] == arr_with_names[0, j]:
            arr_with_names[i, j] = 0

In [19]:
import numpy as np

# 创建一个 16x16 的 ndarray
arr = np.zeros((16, 16))

# 生成循环的行名和列名
row_names = np.tile(np.arange(1, 5), 4)
col_names = np.tile(np.arange(1, 5), 4)

# 在数组的左侧和顶部添加一列和一行
arr_with_names = np.pad(arr, ((1, 0), (1, 0)), mode='constant', constant_values=0)

# 在第一行和第一列分别设置行名和列名
arr_with_names[0, 1:] = col_names
arr_with_names[1:, 0] = row_names


# 将行名和列名相同的单元格的值改为0，其他单元格的值改为1
for i in range(1, arr_with_names.shape[0]):
    for j in range(1, arr_with_names.shape[1]):
        if arr_with_names[i, 0] == arr_with_names[0, j]:
            arr_with_names[i, j] = 0
        else:
            arr_with_names[i, j] = 1

# 打印结果
print(arr_with_names)


[[0. 1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.]
 [2. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1.]
 [3. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [4. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.]
 [2. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1.]
 [3. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [4. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.]
 [2. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1.]
 [3. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [4. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.]
 [2. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1.]
 [3. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [4. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]]
